Feature/add comments
cloudentity/sample-go-mtls-oauth-client pull request #6
Opened 2020-09-25 15:16 UTC by ptrsd

2020-09-28 10:45 UTC, holowinski requested changes

2020-09-28 10:45 UTC, holowinski commented on pkg/acp/client.go
> +	// It assigns a pool with certificates to the HTTP client.
Drop the `it assigns` and change to `assign a pool...` - it's gonna be more consistent with comments in other files.

2020-09-28 10:45 UTC, holowinski commented on pkg/acp/client.go
> +			// It assigns a pool with certificates to the HTTP client.
same

2020-09-28 10:45 UTC, holowinski commented on pkg/acp/client.go
> +	// It sets up the certificate HTTP client needs for TLS communication with a server.
same

2020-09-28 10:45 UTC, holowinski commented on pkg/acp/config.go
> +	// Scopes must be at least a subset of scopes assigned to our application in ACP.
drop `at least`

2020-09-28 10:45 UTC, holowinski commented on pkg/acp/config.go
> +	// AuthURL is an URL where users can authenticate.
Hmm, that's not correct.

https://tools.ietf.org/html/rfc6749#section-3.1

2020-09-28 10:45 UTC, holowinski commented on pkg/acp/config.go
> +	// PKCEEnabled is information whether PKCE is enabled or not.
`is information` is redundant

2020-09-28 10:45 UTC, holowinski commented on pkg/acp/config.go
> +// AuthorizeURL builds the URL where the client will redirect the user after accessing /login endpoint. Challenge is a
This also seems incorrect.

2020-09-28 14:02 UTC, mbilski approved these changes

2020-10-15 15:22 UTC, holowinski commented
Closed this one. Handled in https://github.com/cloudentity/sample-go-mtls-oauth-client/pull/7

2020-10-15 15:22 UTC, closed without merging